// Programming jokes and tech fun facts for the terminal

export const JOKES = [
  "Why do programmers prefer dark mode? Because light attracts bugs!",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "What's a programmer's favorite hangout? The Foo Bar.",
  "Why do Java developers wear glasses? Because they can't C#.",
  "A SQL query walks into a bar, walks up to two tables and asks: Can I join you?",
  "Why did the developer go broke? Because he used up all his cache.",
  "What do you call a programmer from Finland? Nerdic.",
  "How do you comfort a JavaScript bug? You console it.",
  "Why did the programmer get stuck in the shower? The shampoo bottle said: Lather, Rinse, Repeat.",
  "What's the object-oriented way to become wealthy? Inheritance.",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 equals Dec 25.",
  "A programmer's wife tells him: Go to the store and pick up a loaf of bread. If they have eggs, get a dozen. He returns with 12 loaves of bread.",
  "Why don't programmers like nature? It has too many bugs.",
  "What did the router say to the doctor? It hurts when IP.",
  "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
  "What's a programmer's favorite place to hang out? The Git Hub.",
  "Why did the functions stop calling each other? Because they had constant arguments.",
  "What do you call 8 hobbits? A hobbyte.",
  "Why do programmers hate the outdoors? The sunlight causes too many reflections.",
  "How does a programmer fix a broken pizza? With a pizza debugger.",
  "Why did the developer stay calm during the crisis? He had exception handling.",
  "What's the best thing about a Boolean? Even if you're wrong, you're only off by a bit.",
  "Why did the programmer use the entire bottle of shampoo? Because the instructions said: Apply shampoo, rinse, repeat.",
  "What do you call a programmer who doesn't comment their code? A monster.",
  "Why did the programmer always carry a ladder? To reach the cloud.",
  "How do you tell HTML from HTML5? Try it out in Internet Explorer. Did it work? No? It's HTML5.",
  "Why did the database administrator leave his wife? She had one-to-many relationships.",
  "What's the difference between a programmer and a user? A programmer thinks a kilobyte is 1024 bytes, a user thinks it's 1000.",
  "Why do Python programmers prefer snakes? Because they're not into Java.",
  "What did the computer do at lunchtime? Had a byte.",
  "Why was the computer cold? It left its Windows open.",
  "What do you call a computer that sings? A Dell.",
  "Why did the PowerPoint presentation cross the road? To get to the other slide.",
  "What's a computer's favorite snack? Microchips.",
  "Why did the web developer walk out of the restaurant in disgust? The seating was laid out in tables.",
  "There are 10 types of people in the world: those who understand binary and those who don't.",
  "Why was the cell phone wearing glasses? It lost all its contacts.",
  "What's the second best thing about UDP jokes? I don't care if you get them.",
  "I would tell you a UDP joke, but you might not get it.",
  "A QA engineer walks into a bar. Orders a beer. Orders 0 beers. Orders 99999 beers. Orders -1 beers. Orders asdflkj beers.",
  "What do you call a group of 8 hobbits? A hobbyte.",
  "How did the programmer die in the shower? He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
  "Why did the programmer always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
  "A programmer had a problem. He thought, 'I know, I'll use regular expressions.' Now he had two problems.",
  "Real programmers count from 0.",
  "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
  "Why do programmers prefer iOS development? Because on iOS, there are no Windows or Bugs!",
  "What's a pirate's favorite programming language? You'd think it's R, but their first love is the C.",
  "Why did the functions break up? They had constant arguments and couldn't return their feelings.",
  "How do you generate a random string? Put a Windows user in front of Vim and ask them to save and exit.",
  "Why do Java developers wear glasses? Because they don't C#!",
  "ASCII stupid question, get a stupid ANSI.",
  "What do you get when you cross a computer with a lifeguard? A screensaver!",
  "Why did the computer show up at work late? It had a hard drive.",
  "What's an algorithm? A word used by programmers when they don't want to explain what they did.",
  "Why did the database administrator file for divorce? His wife had too many foreign relationships.",
  "I told my computer I needed a break, and now it won't stop sending me Kit-Kats.",
  "Why was the JavaScript developer broke? Because he lost his CENTS (cents)!",
  "What does a baby computer call its father? Data."
];

export const FUN_FACTS = [
  "The first computer bug was an actual bug - a moth found in a computer in 1947.",
  "The first 1GB hard drive weighed over 500 pounds and cost $40,000.",
  "The average person blinks 15-20 times per minute, but only 7 times while using a computer.",
  "The first computer mouse was made of wood.",
  "Email existed before the World Wide Web.",
  "The first domain name ever registered was Symbolics.com on March 15, 1985.",
  "Alaska is the only state that can be typed on one row of a QWERTY keyboard.",
  "The first Apple computer, Apple I, was sold for $666.66.",
  "The first webcam was created at Cambridge University to monitor a coffee pot.",
  "The QWERTY keyboard layout was designed to slow typists down to prevent typewriter jams.",
  "More than 90% of the world's currency only exists on computers.",
  "The original name of Windows was Interface Manager.",
  "The first computer programmer was Ada Lovelace in the 1840s.",
  "The first alarm clock could only ring at 4 AM.",
  "Doug Engelbart invented the computer mouse in 1964, and it was made of wood.",
  "The first video game ever made was Tennis for Two in 1958.",
  "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'.",
  "The @ symbol was chosen for email addresses because it was rarely used.",
  "The first computer virus was created in 1983 and was called 'Elk Cloner'.",
  "HP, Microsoft, and Apple all started in garages.",
  "The average computer user blinks 7 times a minute, less than half the normal rate of 20.",
  "Over 6,000 computer viruses are released every month.",
  "The first banner ad appeared on the internet in 1994.",
  "Bill Gates' house was designed using a Macintosh computer.",
  "The Firefox logo isn't a fox - it's a red panda."
];
