-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create the messages table
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    username TEXT NOT NULL,
    content TEXT NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone (anonymous) to read and write messages
-- NOTE: This is for demonstration purposes. In a real app, you'd want authenticated users.
CREATE POLICY "Enable public access"
ON public.messages
FOR ALL
USING (true)
WITH CHECK (true);

-- 4. Enable Realtime for the messages table
-- This allows the chat to update instantly when new messages are sent.
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
