


CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    username TEXT NOT NULL,
    content TEXT NOT NULL
);


ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable public access"
ON public.messages
FOR ALL
USING (true)
WITH CHECK (true);


ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
